/* Auto-generated by scripts/write-git-version.mjs - do not edit. */
export const appVersion = {
  date: "2026-08-05",
  sha: "814252b",
  branch: "hktrpg-main",
  display: "2026-08-05 814252b hktrpg-main",
} as const;
