/* Auto-generated by scripts/write-git-version.mjs - do not edit. */
export const appVersion = {
  /** Commit time as UTC ISO; format to local timezone in the UI. */
  committedAt: "2026-08-13T13:01:22.000Z",
  sha: "c2dc915",
  branch: "hktrpg-main",
} as const;
