/* Auto-generated by scripts/write-git-version.mjs - do not edit. */
export const appVersion = {
  /** Commit time as UTC ISO; format to local timezone in the UI. */
  committedAt: "2026-08-07T23:21:50.000Z",
  sha: "b636312",
  branch: "ScreenPanel",
} as const;
